#!/bin/sh -e

CARD=${DEVNAME##/dev/snd/hwC}
CARD=${CARD%%D2}

case $PHYSDEVDRIVER in
EMU10K1_Audigy)
  echo -en "\xf0\x00\x20\x21\x61\x00\x00\x00\x7f\x00\xf7" > /dev/snd/midiC${CARD}D1
  /etc/alsa.d/load-soundfont $CARD default.bnk default.sf2
  ;;
sbawe)
  /etc/alsa.d/load-soundfont $CARD default.bnk default.sf2 default.sbk gu11-rom.sf2 GU11-ROM.SF2
  ;;
esac

exit 0
